QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true
QBShared.Jobs = {
	unemployed = { 
		label = 'Sivil', 
		defaultDuty = true, 
		offDutyPay = false, 
		grades = { 
			['0'] = {name = 'Sivil', payment = 25} 
		} 
	},
	police = { 
		label = 'LSPD',
		type = 'unit',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Cadet', payment = 2000},
            ['1'] = {name = 'Officer I', payment = 2600},
            ['2'] = {name = 'Officer II', payment = 2700},
            ['3'] = {name = 'Officer III', payment = 2800},
            ['4'] = {name = 'Officer III+I', payment = 2800},
            ['5'] = {name = 'Sergeant', payment = 2900},
            ['6'] = {name = 'Lieutenant', payment = 2000},
            ['7'] = {name = 'Captain', isboss= true, payment = 2100},
            ['8'] = {name = 'Commander', isboss= true, payment = 2400},
            ['9'] = {name = 'Deputy Chief', isboss= true,  payment = 2600},
            ['10'] = {name = 'Assistant Chief', isboss= true,  payment = 2700},
            ['11'] = {name = 'Chief', isboss= true, payment = 3000},
		},
	},
	usmarshal = { 
		label = 'Marshal',
		type = 'unit',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Cadet', payment = 2000},
            ['1'] = {name = 'Officer I', payment = 2600},
            ['2'] = {name = 'Officer II', payment = 2700},
            ['3'] = {name = 'Officer III', payment = 2800},
            ['4'] = {name = 'Officer III+I', payment = 2800},
            ['5'] = {name = 'Sergeant', payment = 2900},
            ['6'] = {name = 'Lieutenant', payment = 2000},
            ['7'] = {name = 'Captain', isboss= true, payment = 2100},
            ['8'] = {name = 'Commander', isboss= true, payment = 2400},
            ['9'] = {name = 'Deputy Chief', isboss= true,  payment = 2600},
            ['10'] = {name = 'Assistant Chief', isboss= true,  payment = 2700},
            ['11'] = {name = 'Chief', isboss= true, payment = 3000},
		},
	},
	vespuccipd = { 
		label = 'Vinewoood Police Department',
		type = 'unit',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
						['0'] = {name = 'Cadet', payment = 2000},
            ['1'] = {name = 'Officer I', payment = 2600},
            ['2'] = {name = 'Officer II', payment = 2700},
            ['3'] = {name = 'Officer III', payment = 2800},
            ['4'] = {name = 'Officer III+I', payment = 2800},
            ['5'] = {name = 'Sergeant', payment = 2900},
            ['6'] = {name = 'Lieutenant', payment = 2000},
            ['7'] = {name = 'Captain', isboss= true, payment = 2100},
            ['8'] = {name = 'Commander', isboss= true, payment = 2400},
            ['9'] = {name = 'Deputy Chief', isboss= true,  payment = 2600},
            ['10'] = {name = 'Assistant Chief', isboss= true,  payment = 2700},
            ['11'] = {name = 'Chief', isboss= true, payment = 3000},
		},
	},
	bcsd = { 
		label = 'BCSD',
		type = 'unit',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
						['0'] = {name = 'Cadet', payment = 2000},
            ['1'] = {name = 'Officer I', payment = 2600},
            ['2'] = {name = 'Officer II', payment = 2700},
            ['3'] = {name = 'Officer III', payment = 2800},
            ['4'] = {name = 'Officer III+I', payment = 2800},
            ['5'] = {name = 'Sergeant', payment = 2900},
            ['6'] = {name = 'Lieutenant', payment = 2000},
            ['7'] = {name = 'Captain', isboss= true, payment = 2100},
            ['8'] = {name = 'Commander', isboss= true, payment = 2400},
            ['9'] = {name = 'Deputy Chief', isboss= true,  payment = 2600},
            ['10'] = {name = 'Assistant Chief', isboss= true,  payment = 2700},
            ['11'] = {name = 'Chief', isboss= true, payment = 3000},
		},
	},
	pbsd = { 
		label = 'PBSD',
		type = 'unit',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
						['0'] = {name = 'Cadet', payment = 2000},
            ['1'] = {name = 'Officer I', payment = 2600},
            ['2'] = {name = 'Officer II', payment = 2700},
            ['3'] = {name = 'Officer III', payment = 2800},
            ['4'] = {name = 'Officer III+I', payment = 2800},
            ['5'] = {name = 'Sergeant', payment = 2900},
            ['6'] = {name = 'Lieutenant', payment = 2000},
            ['7'] = {name = 'Captain', isboss= true, payment = 2100},
            ['8'] = {name = 'Commander', isboss= true, payment = 2400},
            ['9'] = {name = 'Deputy Chief', isboss= true,  payment = 2600},
            ['10'] = {name = 'Assistant Chief', isboss= true,  payment = 2700},
            ['11'] = {name = 'Chief', isboss= true, payment = 3000},
		},
	},
	lssp = { 
		label = 'San Andreas Highway Patrol',
		type = 'unit',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
						['0'] = {name = 'Cadet', payment = 2000},
            ['1'] = {name = 'Officer I', payment = 2600},
            ['2'] = {name = 'Officer II', payment = 2700},
            ['3'] = {name = 'Officer III', payment = 2800},
            ['4'] = {name = 'Officer III+I', payment = 2800},
            ['5'] = {name = 'Sergeant', payment = 2900},
            ['6'] = {name = 'Lieutenant', payment = 2000},
            ['7'] = {name = 'Captain', isboss= true, payment = 2100},
            ['8'] = {name = 'Commander', isboss= true, payment = 2400},
            ['9'] = {name = 'Deputy Chief', isboss= true,  payment = 2600},
            ['10'] = {name = 'Assistant Chief', isboss= true,  payment = 2700},
            ['11'] = {name = 'Chief', isboss= true, payment = 3000},
		},
	},
	lspr = { 
		label = 'LSPR',
		type = 'unit',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
						['0'] = {name = 'Cadet', payment = 2000},
            ['1'] = {name = 'Officer I', payment = 2600},
            ['2'] = {name = 'Officer II', payment = 2700},
            ['3'] = {name = 'Officer III', payment = 2800},
            ['4'] = {name = 'Officer III+I', payment = 2800},
            ['5'] = {name = 'Sergeant', payment = 2900},
            ['6'] = {name = 'Lieutenant', payment = 2000},
            ['7'] = {name = 'Captain', isboss= true, payment = 2100},
            ['8'] = {name = 'Commander', isboss= true, payment = 2400},
            ['9'] = {name = 'Deputy Chief', isboss= true,  payment = 2600},
            ['10'] = {name = 'Assistant Chief', isboss= true,  payment = 2700},
            ['11'] = {name = 'Chief', isboss= true, payment = 3000},
		},
	},
	dsd = { 
		label = 'DSD',
		type = 'unit',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
						['0'] = {name = 'Cadet', payment = 2000},
            ['1'] = {name = 'Officer I', payment = 2600},
            ['2'] = {name = 'Officer II', payment = 2700},
            ['3'] = {name = 'Officer III', payment = 2800},
            ['4'] = {name = 'Officer III+I', payment = 2800},
            ['5'] = {name = 'Sergeant', payment = 2900},
            ['6'] = {name = 'Lieutenant', payment = 2000},
            ['7'] = {name = 'Captain', isboss= true, payment = 2100},
            ['8'] = {name = 'Commander', isboss= true, payment = 2400},
            ['9'] = {name = 'Deputy Chief', isboss= true,  payment = 2600},
            ['10'] = {name = 'Assistant Chief', isboss= true,  payment = 2700},
            ['11'] = {name = 'Chief', isboss= true, payment = 3000},
		},
	},
	doj = {
			label = 'DOJ',
			type = 'unit',
			defaultDuty = true,
			offDutyPay = false,
			grades = {
				['0'] = {name = 'Lawyer', payment = 2250},
				['1'] = {name = 'Judge', payment = 2500},
				['2'] = {name = 'Prosecutor', payment = 2750},
				['3'] = {name = 'Head Prosecutor',isboss= true, payment = 3000},
			},
		},
	ambulance = {
		label = 'LSMS',
		type = 'ambulance',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Recruit', payment = 3500},
			['1'] = {name = 'Paramedic', payment = 4000},
			['2'] = {name = 'Doctor', payment = 4750},
			['3'] = {name = 'Surgeon', payment = 5500},
			['4'] = {name = 'Chief', isboss = true, payment = 6660},
		},
	},
	kilise = {
		label = 'kilise',
		type = 'kilise',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Rahip', payment = 100},
			['1'] = {name = 'Rahibe', payment = 150},
			['2'] = {name = 'Baş Rahip', payment = 200},
			['3'] = {name = 'Baş Piskopos', payment = 250},
			['4'] = {name = 'Kardinal', payment = 250},
			['5'] = {name = 'Papaz', isboss = true, payment = 350},
		},
	},
	mechanic_bennys = {
		label = 'Bennys Mechanic',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Usta', payment = 15},
			['2'] = {name = 'Müdür', payment = 20},
			['3'] = {name = 'Patron', isboss = true, payment = 25},
		},
	},
	afterlife = {
		label = 'Afterlife Mechanic',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Usta', payment = 15},
			['2'] = {name = 'Müdür', payment = 20},
			['3'] = {name = 'Patron', isboss = true, payment = 25},
		},
	},
	mechanic_lscustom = {
		label = 'LS Custom Mechanic',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Usta', payment = 15},
			['2'] = {name = 'Müdür', payment = 20},
			['3'] = {name = 'Patron', isboss = true, payment = 25},
		},
	},
	mechanic_lscustom2 = {
		label = 'LS Custom 2 Mechanic',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Usta', payment = 15},
			['2'] = {name = 'Müdür', payment = 20},
			['3'] = {name = 'Patron', isboss = true, payment = 25},
		},
	},
	mechanic_airport = {
		label = 'Airport Mechanic',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Usta', payment = 10},
			['2'] = {name = 'Müdür', payment = 20},
			['3'] = {name = 'Patron', isboss = true, payment = 25},
		},
	},
	mechanic_oldhayes = {
		label = 'Old Hayes Mechanic',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Usta', payment = 10},
			['2'] = {name = 'Müdür', payment = 20},
			['3'] = {name = 'Patron', isboss = true, payment = 25},
		},
	},
	mechanic_hayes = {
		label = 'Hayes Mechanic',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Usta', payment = 10},
			['2'] = {name = 'Müdür', payment = 20},
			['3'] = {name = 'Patron', isboss = true, payment = 25},
		},
	},
	mechanic_japanese = {
		label = 'Japanese Mechanic',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Usta', payment = 10},
			['2'] = {name = 'Müdür', payment = 20},
			['3'] = {name = 'Patron', isboss = true, payment = 25},
		},
	},
	mechanic_illegal = {
		label = 'İllegal Mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 50},
			['1'] = {name = 'Usta', payment = 10},
			['2'] = {name = 'Müdür', payment = 15},
			['3'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	sons = {
		label = 'Sons of Mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 50},
			['1'] = {name = 'Usta', payment = 100},
			['2'] = {name = 'Müdür', payment = 150},
			['3'] = {name = 'Patron', isboss = true, payment = 200},
		},
	},
	mechanic_ottos = {
		label = 'Ottos Mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 50},
			['1'] = {name = 'Usta', payment = 100},
			['2'] = {name = 'Müdür', payment = 150},
			['3'] = {name = 'Patron', isboss = true, payment = 200},
		},
	},
	mprestaurant = {
		label = 'Mirror Park Restaurant',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 5},
			['1'] = {name = 'Usta', payment = 10},
			['2'] = {name = 'Müdür', payment = 15},
			['3'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	uwucafe = {
		label = 'UwU Cafe',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	weazel = {
		label = 'Weazel News',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 100},
			['1'] = {name = 'Müdür', payment = 145},
			['2'] = {name = 'Patron', isboss = true, payment = 180},
		},
	},
	wedshop = {
		label = 'Weedshop',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	pondcafe = {
		label = 'Pond Cafe',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	lojistik = {
		label = 'Lost w Drugs',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	sacred = {
		label = 'Sacred',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	grancafe = {
		label = 'Cranberry',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	nightclub = {
		label = 'Night Club',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	cute = {
		label = 'Coffe Cute',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 10},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	mai10 = {
		label = 'Maisonette10',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	beanmachine = {
		label = 'Beanmachine',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	popeyes = {
		label = 'Popeyes',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	motelcafe = {
		label = 'Motel Cafe',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	koi = {
		label = 'KOİ',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	plaza = {
		label = 'plaza',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	pizza = { 
		label = 'Pizzaria',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	coolcafe = {
		label = 'COOLBEANS',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	susi = {
		label = 'Susi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	unicorn = { 
		label = 'Unicorn',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	burgershot = {
		label = 'Burger Shot',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	hornys = {
		label = 'Horny`s Burger',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	taco = {
		label = 'Taco',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	bahama = {
		label = 'Bahama',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	ballas = {
		label = 'Ballas Records',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	atom = {
		label = 'ATOM UP',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	icecream = {
		label = 'Polar IC Cream',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	jons = {
		label = 'Jons Cafe',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	iskelebar = {
		label = 'Elite Bar',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},

	pitstop = {
		label = 'Pitstop',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	redline = {
		label = 'Sugar Mekanik',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},

	yellowjack = {
		label = 'YellowJack',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},

	tequila = {
		label = 'Tequila',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	irishpub = {
		label = 'Irish Pub',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	club77 = {
		label = 'CLUB77',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 15},
			['1'] = {name = 'Müdür', payment = 20},
			['2'] = {name = 'Patron', isboss = true, payment = 25},
		},
	},
	ammunation = {
		label = 'Ammunation',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	gunshop_one = {
		label = 'Gun Shop',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	gunshop_two = {
		label = 'Gun Shop',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	gunshop_thre = {
		label = 'Gun Shop',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	usedcar = {
		label = '2.El Galeri',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	cardealer = {
		label = 'Galeri',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	cryptoexchange = {
		label = 'Crypto Exchange',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	realestate = {
		label = 'Emlak',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	vibecafe = {
		label = 'Roso Cafe',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
	},
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
					['0'] = {name = 'Çalışan', payment = 10},
			['1'] = {name = 'Müdür', payment = 15},
			['2'] = {name = 'Patron', isboss = true, payment = 20},
		},
		
	},
}