QBShared = QBShared or {}
QBShared.Vehicles = QBShared.Vehicles or {}

local Vehicles = {
    { model = 'blista',          name = 'Blista',                        brand = 'Dinka',           price = 53000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'brioso',          name = 'Brioso R/A',                    brand = 'Grotti',          price = 64000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'club',            name = 'Club',                          brand = 'BF',              price = 48000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'dilettante',      name = 'Dilettante',                    brand = 'Karin',           price = 49000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'dilettante2',     name = 'Dilettante Patrol',             brand = 'Karin',           price = 52000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'kanjo',           name = 'Blista Kanjo',                  brand = 'Dinka',           price = 52000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'issi2',           name = 'Issi',                          brand = 'Weeny',           price = 44000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'issi3',           name = 'Issi Classic',                  brand = 'Weeny',           price = 34000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'issi4',           name = 'Issi Arena',                    brand = 'Weeny',           price = 68000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'issi5',           name = 'Issi Future Shock',             brand = 'Weeny',           price = 68000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'issi6',           name = 'Issi Nightmare',                brand = 'Weeny',           price = 68000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'panto',           name = 'Panto',                         brand = 'Benefactor',      price = 72000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'prairie',         name = 'Prairie',                       brand = 'Bollokan',        price = 70000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'rhapsody',        name = 'Rhapsody',                      brand = 'Declasse',        price = 64000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'brioso2',         name = 'Brioso 300',                    brand = 'Grotti',          price = 56000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'weevil',          name = 'Weevil',                        brand = 'BF',              price = 49000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'issi7',           name = 'Issi Sport',                    brand = 'Weeny',           price = 150000,  category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'blista2',         name = 'Blista Compact',                brand = 'Dinka',           price = 58950,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'blista3',         name = 'Blista Go Go Monkey',           brand = 'Dinka',           price = 59000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'brioso3',         name = 'Brioso 300 Widebody',           brand = 'Grotti',          price = 83750,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'boor',            name = 'Boor',                          brand = 'Karin',           price = 63000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    --- Sedans (1)
    { model = 'asea',            name = 'Asea',                          brand = 'Declasse',        price = 45000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'asterope',        name = 'Asterope',                      brand = 'Karin',           price = 55000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'cog55',           name = 'Cognoscenti 55',                brand = 'Enus',            price = 62000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'cognoscenti',     name = 'Cognoscenti',                   brand = 'Enus',            price = 62500,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'emperor',         name = 'Emperor',                       brand = 'Albany',          price = 4250,    category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'fugitive',        name = 'Fugitive',                      brand = 'Cheval',          price = 64000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'glendale',        name = 'Glendale',                      brand = 'Benefactor',      price = 44000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'glendale2',       name = 'Glendale Custom',               brand = 'Benefactor',      price = 56000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'ingot',           name = 'Ingot',                         brand = 'Vulcar',          price = 4999,    category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'intruder',        name = 'Intruder',                      brand = 'Karin',           price = 55250,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'premier',         name = 'Premier',                       brand = 'Declasse',        price = 56000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'primo',           name = 'Primo',                         brand = 'Albany',          price = 5000,    category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'primo2',          name = 'Primo Custom',                  brand = 'Albany',          price = 54500,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'regina',          name = 'Regina',                        brand = 'Dundreary',       price = 11000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'stafford',        name = 'Stafford',                      brand = 'Enus',            price = 190000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'stanier',         name = 'Stanier',                       brand = 'Vapid',           price = 63000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'stratum',         name = 'Stratum',                       brand = 'Zirconium',       price = 59000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'stretch',         name = 'Stretch',                       brand = 'Dundreary',       price = 540000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'superd',          name = 'Super Diamond',                 brand = 'Enus',            price = 160000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'surge',           name = 'Surge',                         brand = 'Cheval',          price = 64000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'tailgater',       name = 'Tailgater',                     brand = 'Obey',            price = 62000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'warrener',        name = 'Warrener',                      brand = 'Vulcar',          price = 44000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'washington',      name = 'Washington',                    brand = 'Albany',          price = 11000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'tailgater2',      name = 'Tailgater S',                   brand = 'Obey',            price = 95000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'cinquemila',      name = 'Lampadati',                     brand = 'Cinquemila',      price = 100000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'iwagen',          name = 'Obey',                          brand = 'I-Wagen',         price = 140000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'astron',          name = 'Astron',                        brand = 'Pfister',         price = 190000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'baller7',         name = 'Baller ST',                     brand = 'Gallivanter',     price = 185000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'comet7',          name = 'Comet',                         brand = 'S2 Cabrio',       price = 210000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'deity',           name = 'Deity',                         brand = 'Enus',            price = 372500,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'jubilee',         name = 'Jubilee',                       brand = 'Enus',            price = 525000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'oracle',          name = 'Oracle',                        brand = 'Übermacht',       price = 62000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'schafter2',       name = 'Schafter',                      brand = 'Benefactor',      price = 72500,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'rhinehart',       name = 'Rhinehart',                     brand = 'Übermacht',       price = 95000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'eudora',          name = 'Eudora',                        brand = 'Willard',         price = 57000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'asterope2',       name = 'Asterope GZ',                   brand = 'Karin',           price = 95000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'impaler5',        name = 'Impaler SZ',                    brand = 'Declasse',        price = 79000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    --- SUV (2)
    { model = 'baller',          name = 'Baller',                        brand = 'Gallivanter',     price = 62000,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'baller2',         name = 'Baller II',                     brand = 'Gallivanter',     price = 105000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'baller3',         name = 'Baller LE',                     brand = 'Gallivanter',     price = 110000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'baller4',         name = 'Baller LE LWB',                 brand = 'Gallivanter',     price = 120000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'bjxl',            name = 'BeeJay XL',                     brand = 'Karin',           price = 91000,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'cavalcade',       name = 'Cavalcade',                     brand = 'Albany',          price = 54000,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'cavalcade2',      name = 'Cavalcade II',                  brand = 'Albany',          price = 60500,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'contender',       name = 'Contender',                     brand = 'Vapid',           price = 150000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'dubsta',          name = 'Dubsta',                        brand = 'Benefactor',      price = 107500,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'dubsta2',         name = 'Dubsta pdm',                    brand = 'Benefactor',      price = 110000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'fq2',             name = 'FQ2',                           brand = 'Fathom',          price = 67500,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'granger',         name = 'Granger',                       brand = 'Declasse',        price = 96000,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'gresley',         name = 'Gresley',                       brand = 'Bravado',         price = 79000,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'habanero',        name = 'Habanero',                      brand = 'Emperor',         price = 64000,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'huntley',         name = 'Huntley S',                     brand = 'Enus',            price = 68500,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'landstalker',     name = 'Landstalker',                   brand = 'Dundreary',       price = 56000,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'landstalker2',    name = 'Landstalker XL',                brand = 'Dundreary',       price = 105000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'novak',           name = 'Novak',                         brand = 'Lampadati',       price = 105000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'patriot',         name = 'Patriot',                       brand = 'Mammoth',         price = 105000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'patriot2',        name = 'Patriot Stretch',               brand = 'Mammoth',         price = 180000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'radi',            name = 'Radius',                        brand = 'Vapid',           price = 58000,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'rebla',           name = 'Rebla GTS',                     brand = 'Übermacht',       price = 125000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'rocoto',          name = 'Rocoto',                        brand = 'Obey',            price = 73000,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'seminole',        name = 'Seminole',                      brand = 'Canis',           price = 64000,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'seminole2',       name = 'Seminole Frontier',             brand = 'Canis',           price = 73000,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'serrano',         name = 'Serrano',                       brand = 'Benefactor',      price = 69000,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'toros',           name = 'Toros',                         brand = 'Pegassi',         price = 94000,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'xls',             name = 'XLS',                           brand = 'Benefactor',      price = 91000,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'granger2',        name = 'Granger 3600LX',                brand = 'Declasse',        price = 107000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'patriot3',        name = 'Patriot Military',              brand = 'Mil-Spec',        price = 230000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'aleutian',        name = 'Aleutian',                      brand = 'Vapid',           price = 185500,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'baller8',         name = 'Baller ST-D',                   brand = 'Gallivanter',     price = 211500,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'cavalcade3',      name = 'Cavalcade XL',                  brand = 'Albany',          price = 184500,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'dorado',          name = 'Dorado',                        brand = 'Bravado',         price = 97500,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'vivanite',        name = 'Vivanite',                      brand = 'Karin',           price = 97500,   category = 'suvs',           type = 'automobile', shop = 'pdm' },
    --- Coupes (3)
    { model = 'cogcabrio',       name = 'Cognoscenti Cabrio',            brand = 'Enus',            price = 70000,   category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'exemplar',        name = 'Exemplar',                      brand = 'Dewbauchee',      price = 84000,   category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'f620',            name = 'F620',                          brand = 'Ocelot',          price = 122500,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'felon',           name = 'Felon',                         brand = 'Lampadati',       price = 75000,   category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'felon2',          name = 'Felon GT',                      brand = 'Lampadati',       price = 94000,   category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'jackal',          name = 'Jackal',                        brand = 'Ocelot',          price = 67000,   category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'oracle2',         name = 'Oracle XS',                     brand = 'Übermacht',       price = 72000,   category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'sentinel',        name = 'Sentinel',                      brand = 'Übermacht',       price = 74000,   category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'sentinel2',       name = 'Sentinel XS',                   brand = 'Übermacht',       price = 77000,   category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'windsor',         name = 'Windsor',                       brand = 'Enus',            price = 190000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'windsor2',        name = 'Windsor Drop',                  brand = 'Enus',            price = 215000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'zion',            name = 'Zion',                          brand = 'Übermacht',       price = 62000,   category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'zion2',           name = 'Zion Cabrio',                   brand = 'Übermacht',       price = 88000,   category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'champion',        name = 'Champion',                      brand = 'Dewbauchee',      price = 255000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'futo',            name = 'Futo',                          brand = 'Karin',           price = 57000,   category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'sentinel3',       name = 'Sentinel Classic',              brand = 'Übermacht',       price = 89000,   category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'kanjosj',         name = 'Kanjo SJ',                      brand = 'Dinka',           price = 120000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'postlude',        name = 'Postlude',                      brand = 'Dinka',           price = 105000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'tahoma',          name = 'Tahoma Coupe',                  brand = 'Declasse',        price = 56000,   category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'broadway',        name = 'Broadway',                      brand = 'Classique',       price = 60000,   category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'fr36',            name = 'FR36',                          brand = 'Fathom',          price = 115000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    --- Muscle (4)
    { model = 'blade',           name = 'Blade',                         brand = 'Vapid',           price = 63500,   category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'buccaneer',       name = 'Buccaneer',                     brand = 'Albany',          price = 62500,   category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'buccaneer2',      name = 'Buccaneer Rider',               brand = 'Albany',          price = 64500,   category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'chino',           name = 'Chino',                         brand = 'Vapid',           price = 44000,   category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'chino2',          name = 'Chino Luxe',                    brand = 'Vapid',           price = 44000,   category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'clique',          name = 'Clique',                        brand = 'Vapid',           price = 64000,   category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'coquette3',       name = 'Coquette BlackFin',             brand = 'Invetero',        price = 104000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'deviant',         name = 'Deviant',                       brand = 'Schyster',        price = 74000,   category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'dominator',       name = 'Dominator',                     brand = 'Vapid',           price = 102500,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'dominator2',      name = 'Pißwasser Dominator',           brand = 'Vapid',           price = 94000,   category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'dominator3',      name = 'Dominator GTX',                 brand = 'Vapid',           price = 114000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'dominator7',      name = 'Dominator ASP',                 brand = 'Vapid',           price = 113000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'dominator8',      name = 'Dominator GTT',                 brand = 'Vapid',           price = 92500,   category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'bati',            name = 'Bati 801',                      brand = 'Pegassi',         price = 104000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'bati2',           name = 'Bati 801RR',                    brand = 'Pegassi',         price = 124000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'carbonrs',        name = 'Carbon RS',                     brand = 'Nagasaki',        price = 139000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'defiler',         name = 'Defiler',                       brand = 'Shitzu',          price = 103000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'diablous',        name = 'Diablous',                      brand = 'Principe',        price = 103000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'diablous2',       name = 'Diablous Custom',               brand = 'Principe',        price = 124500,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },  -- %15 indirim
    { model = 'double',          name = 'Double-T',                      brand = 'Dinka',           price = 165000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'fcr2',            name = 'FCR 1000 Custom',               brand = 'Pegassi',         price = 92500,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'lectro',          name = 'Lectro',                        brand = 'Principe',        price = 111000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'stryder',         name = 'Stryder',                       brand = 'Nagasaki',        price = 113000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },  -- %15 indirim
    { model = 'thrust',          name = 'Thrust',                        brand = 'Dinka',           price = 159000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'akuma',           name = 'Akuma',                         brand = 'Dinka',           price = 140000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'bf400',           name = 'BF400',                         brand = 'Nagasaki',        price = 129000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'manchez2',        name = 'Manchez Scout',                 brand = 'Maibatsu',        price = 113000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },  -- %15 indirim
    { model = 'shinobi',         name = 'Shinobi',                       brand = 'Nagasaki',        price = 128000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },  -- %15 indirim
    { model = 'reever',          name = 'Reever',                        brand = 'Western',         price = 142000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },  -- %15 indirim
    { model = 'vortex',          name = 'Vortex',                        brand = 'Pegassi',         price = 124000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'nightblade',      name = 'Nightblade',                    brand = 'Western',         price = 129500,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'hakuchou',        name = 'Hakuchou',                      brand = 'Shitzu',          price = 129000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'hakuchou2',       name = 'Hakuchou Drag',                 brand = 'Shitzu',          price = 160500,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },  -- %15 indirim
    { model = 'zombieb',         name = 'Zombie',                        brand = 'Chopper',         price = 125000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'zombiea',         name = 'Zombie',                        brand = 'Bobber',          price = 110000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'daemon',          name = 'Daemon',                        brand = 'Daemon',          price = 123000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'daemon2',         name = 'Daemon',                        brand = 'Daemon 2',        price = 123000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'avarus',          name = 'Avarus',                        brand = 'Avarus',          price = 134000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'sanctus',         name = 'Sanctus',                       brand = 'Zombie',          price = 165000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'hexer',           name = 'Hexer',                         brand = 'Hexer',           price = 124000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'yosemite3',       name = 'Yosemite Rancher',              brand = 'Declasse',        price = 75000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'mesa',            name = 'Mesa',                          brand = 'Canis',           price = 95000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'sandking',        name = 'Sandking XL',                   brand = 'Vapid',           price = 180000,  category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'kamacho',         name = 'Kamacho',                       brand = 'Canis',           price = 175000,  category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'everon',          name = 'Everon',                        brand = 'Karin',           price = 205000,  category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'caracara2',       name = 'Caracara XL',                   brand = 'Vadip',           price = 215000,  category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'dubsta3',         name = 'Dubsta 6x6',                    brand = 'Annis',           price = 160000,  category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'freecrawler',     name = 'Freecrawler',                   brand = 'Canis',           price = 135000,  category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'riata',           name = 'Riata',                         brand = 'Vadip',           price = 95000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'brawler',         name = 'Brawler',                       brand = 'Coil',            price = 165000,  category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'bfinjection',     name = 'Bf Injection',                  brand = 'Annis',           price = 45000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'bifta',           name = 'Bifta',                         brand = 'Annis',           price = 65000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'ardent',          name = 'Ardent',                        brand = 'Ocelot',          price = 128000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'btype',           name = 'Roosevelt',                     brand = 'Albany',          price = 115000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'btype2',          name = 'Franken Stange',                brand = 'Albany',          price = 127000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'btype3',          name = 'Roosevelt Valor',               brand = 'Albany',          price = 103000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'casco',           name = 'Casco',                         brand = 'Lampadati',       price = 77500,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'dynasty',         name = 'Dynasty',                       brand = 'Weeny',           price = 69000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'fagaloa',         name = 'Fagaloa',                       brand = 'Vulcar',          price = 73000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'feltzer3',        name = 'Stirling GT',                   brand = 'Benefactor',      price = 155000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'gt500',           name = 'GT500',                         brand = 'Grotti',          price = 96000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'infernus2',       name = 'Infernus Classic',              brand = 'Pegassi',         price = 285000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'jb7002',          name = 'JB 700W',                       brand = 'Dewbauchee',      price = 84000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'mamba',           name = 'Mamba',                         brand = 'Declasse',        price = 115000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'michelli',        name = 'Michelli GT',                   brand = 'Lampadati',       price = 74000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'monroe',          name = 'Monroe',                        brand = 'Pegassi',         price = 155000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'nebula',          name = 'Nebula',                        brand = 'Vulcar',          price = 62000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'peyote',          name = 'Peyote',                        brand = 'Vapid',           price = 63500,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'peyote3',         name = 'Peyote Custom',                 brand = 'Vapid',           price = 88000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'pigalle',         name = 'Pigalle',                       brand = 'Lampadati',       price = 66500,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'rapidgt3',        name = 'Rapid GT Classic',              brand = 'Dewbauchee',      price = 94000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'retinue',         name = 'Retinue',                       brand = 'Vapid',           price = 72000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'retinue2',        name = 'Retinue MKII',                  brand = 'Vapid',           price = 78000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'savestra',        name = 'Savestra',                      brand = 'Annis',           price = 92000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'stinger',         name = 'Stinger',                       brand = 'Grotti',          price = 95000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'stingergt',       name = 'Stinger GT',                    brand = 'Grotti',          price = 105000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'swinger',         name = 'Swinger',                       brand = 'Ocelot',          price = 175000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'torero',          name = 'Torero',                        brand = 'Pegassi',         price = 135000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'tornado',         name = 'Tornado',                       brand = 'Declasse',        price = 65000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'tornado2',        name = 'Tornado Convertible',           brand = 'Declasse',        price = 66000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'tornado5',        name = 'Tornado Custom',                brand = 'Declasse',        price = 66000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'turismo2',        name = 'Turismo Classic',               brand = 'Grotti',          price = 210000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'viseris',         name = 'Viseris',                       brand = 'Lampadati',       price = 160000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'z190',            name = '190Z',                          brand = 'Karin',           price = 118000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'ztype',           name = 'Z-Type',                        brand = 'Truffade',        price = 310000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'zion3',           name = 'Zion Classic',                  brand = 'Übermacht',       price = 69000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'cheburek',        name = 'Cheburek',                      brand = 'Rune',            price = 11000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'toreador',        name = 'Toreador',                      brand = 'Pegassi',         price = 115650,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'peyote2',         name = 'Peyote Gasser',                 brand = 'Vapid',           price = 84000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'coquette2',       name = 'Coquette Classic',              brand = 'Invetero',        price = 105000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'alpha',           name = 'Alpha',                         brand = 'Albany',          price = 93000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'banshee',         name = 'Banshee',                       brand = 'Bravado',         price = 96000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'bestiagts',       name = 'Bestia GTS',                    brand = 'Grotti',          price = 77000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'buffalo',         name = 'Buffalo',                       brand = 'Bravado',         price = 58750,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'buffalo2',        name = 'Buffalo S',                     brand = 'Bravado',         price = 64500,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'carbonizzare',    name = 'Carbonizzare',                  brand = 'Grotti',          price = 195000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'comet2',          name = 'Comet',                         brand = 'Pfister',         price = 170000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'comet3',          name = 'Comet Retro Custom',            brand = 'Pfister',         price = 215000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'comet4',          name = 'Comet Safari',                  brand = 'Pfister',         price = 150000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'comet5',          name = 'Comet SR',                      brand = 'Pfister',         price = 195000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'coquette',        name = 'Coquette',                      brand = 'Invetero',        price = 185000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'coquette4',       name = 'Coquette D10',                  brand = 'Invetero',        price = 260000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'drafter',         name = '8F Drafter',                    brand = 'Obey',            price = 120000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'elegy',           name = 'Elegy Retro Custom',            brand = 'Annis',           price = 185000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'elegy2',          name = 'Elegy RH8',                     brand = 'Annis',           price = 190000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'feltzer2',        name = 'Feltzer',                       brand = 'Benefactor',      price = 136000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'flashgt',         name = 'Flash GT',                      brand = 'Vapid',           price = 88000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'furoregt',        name = 'Furore GT',                     brand = 'Lampadati',       price = 118000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'gb200',           name = 'GB 200',                        brand = 'Vapid',           price = 180000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'komoda',          name = 'Komoda',                        brand = 'Lampadati',       price = 95000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'imorgon',         name = 'Imorgon',                       brand = 'Överflöd',        price = 160000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'italigto',        name = 'Itali GTO',                     brand = 'Progen',          price = 300000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'jugular',         name = 'Jugular',                       brand = 'Ocelot',          price = 120000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'jester',          name = 'Jester',                        brand = 'Dinka',           price = 172250,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'jester2',         name = 'Jester Racecar',                brand = 'Dinka',           price = 250000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'jester3',         name = 'Jester Classic',                brand = 'Dinka',           price = 122500,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'khamelion',       name = 'Khamelion',                     brand = 'Hijak',           price = 94000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'kuruma',          name = 'Kuruma',                        brand = 'Karin',           price = 106000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'kuruma2',         name = 'kuruma2',                       brand = 'Karin2',          price = 106000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'locust',          name = 'Locust',                        brand = 'Ocelot',          price = 240000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'lynx',            name = 'Lynx',                          brand = 'Ocelot',          price = 190000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'massacro',        name = 'Massacro',                      brand = 'Dewbauchee',      price = 150000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'massacro2',       name = 'Massacro Racecar',              brand = 'Dewbauchee',      price = 114000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'neo',             name = 'Neo',                           brand = 'Vysser',          price = 270000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'neon',            name = 'Neon',                          brand = 'Pfister',         price = 260000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'ninef',           name = '9F',                            brand = 'Obey',            price = 99000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'ninef2',          name = '9F Cabrio',                     brand = 'Obey',            price = 115000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'omnis',           name = 'Omnis',                         brand = 'Wow',             price = 94000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'paragon',         name = 'Paragon',                       brand = 'Enus',            price = 94000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'pariah',          name = 'Pariah',                        brand = 'Ocelot',          price = 94000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'penumbra',        name = 'Penumbra',                      brand = 'Maibatsu',        price = 62000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'penumbra2',       name = 'Penumbra FF',                   brand = 'Maibatsu',        price = 74000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'rapidgt',         name = 'Rapid GT',                      brand = 'Dewbauchee',      price = 126000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'rapidgt2',        name = 'Rapid GT Convertible',          brand = 'Dewbauchee',      price = 130000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'raptor',          name = 'Raptor',                        brand = 'BF',              price = 124000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'revolter',        name = 'Revolter',                      brand = 'Übermacht',       price = 129000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'ruston',          name = 'Ruston',                        brand = 'Hijak',           price = 170000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'schafter3',       name = 'Schafter V12',                  brand = 'Benefactor',      price = 79000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'schafter4',       name = 'Schafter LWB',                  brand = 'Benefactor',      price = 61000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'schlagen',        name = 'Schlagen GT',                   brand = 'Benefactor',      price = 200000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'schwarzer',       name = 'Schwartzer',                    brand = 'Benefactor',      price = 91000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'seven70',         name = 'Seven-70',                      brand = 'Dewbauchee',      price = 180000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'specter',         name = 'Specter',                       brand = 'Dewbauchee',      price = 200000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'streiter',        name = 'Streiter',                      brand = 'Benefactor',      price = 64000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'sugoi',           name = 'Sugoi',                         brand = 'Dinka',           price = 125000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'sultan',          name = 'Sultan',                        brand = 'Karin',           price = 94000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'sultan2',         name = 'Sultan Custom',                 brand = 'Karin',           price = 99000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'surano',          name = 'Surano',                        brand = 'Benefactor',      price = 124000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'tropos',          name = 'Tropos Rallye',                 brand = 'Lampadati',       price = 105000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'verlierer2',      name = 'Verlierer',                     brand = 'Bravado',         price = 134500,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'vstr',            name = 'V-STR',                         brand = 'Albany',          price = 124000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'italirsx',        name = 'Itali RSX',                     brand = 'Progen',          price = 300000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'zr350',           name = 'ZR350',                         brand = 'Annis',           price = 78000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'calico',          name = 'Calico GTF',                    brand = 'Karin',           price = 79000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'futo2',           name = 'Futo GTX',                      brand = 'Karin',           price = 79000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'jester4',         name = 'Jester RR',                     brand = 'Dinka',           price = 280000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'remus',           name = 'Remus',                         brand = 'Annis',           price = 92000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'comet6',          name = 'Comet S2',                      brand = 'Pfister',         price = 270000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'growler',         name = 'Growler',                       brand = 'Pfister',         price = 245000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'vectre',          name = 'Vectre',                        brand = 'Emperor',         price = 124000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'cypher',          name = 'Cypher',                        brand = 'Übermacht',       price = 195000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'sultan3',         name = 'Sultan Classic Custom',         brand = 'Karin',           price = 99000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'rt3000',          name = 'RT3000',                        brand = 'Dinka',           price = 95000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'sultanrs',        name = 'Sultan RS',                     brand = 'Karin',           price = 116500,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'visione',         name = 'Visione',                       brand = 'Grotti',          price = 790000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'cheetah2',        name = 'Cheetah Classic',               brand = 'Grotti',          price = 235000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'stingertt',       name = 'Itali GTO Stinger TT',          brand = 'Maibatsu',        price = 278000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'omnisegt',        name = 'Omnis e-GT',                    brand = 'Obey',            price = 225000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'sentinel4',       name = 'Sentinel Classic Widebody',     brand = 'Übermacht',       price = 180000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'sm722',           name = 'SM722',                         brand = 'Benefactor',      price = 165000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'tenf',            name = '10F',                           brand = 'Obey',            price = 225000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'tenf2',           name = '10F Widebody',                  brand = 'Obey',            price = 255000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'everon2',         name = 'Everon Hotring',                brand = 'Karin',           price = 84000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'issi8',           name = 'Issi Rally',                    brand = 'Weeny',           price = 99000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'corsita',         name = 'Corsita',                       brand = 'Lampadati',       price = 94000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'gauntlet6',       name = 'Hotring Hellfire',              brand = 'Bravado',         price = 221000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'coureur',         name = 'La Coureuse',                   brand = 'Penaud',          price = 239000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'r300',            name = '300R',                          brand = 'Annis',           price = 100000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'panthere',        name = 'Panthere',                      brand = 'Toundra',         price = 90000,   category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'paragon3',        name = 'Paragon S',                     brand = 'Enus',            price = 260000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'eurosX32',        name = 'Euros X32',                     brand = 'Annis',           price = 220000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'coquette5',       name = 'Coquette D1',                   brand = 'Invetero',        price = 260000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'pipistrello',     name = 'Pipistrello',                   brand = 'Overflod',        price = 280000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'niobe',           name = 'Niobe',                         brand = 'Ubermacht',       price = 220000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'adder',           name = 'Adder',                         brand = 'Truffade',        price = 435000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'autarch',         name = 'Autarch',                       brand = 'Överflöd',        price = 392000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'banshee2',        name = 'Banshee 900R',                  brand = 'Bravado',         price = 490000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'bullet',          name = 'Bullet',                        brand = 'Vapid',           price = 390000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'cheetah',         name = 'Cheetah',                       brand = 'Grotti',          price = 390000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'cyclone',         name = 'Cyclone',                       brand = 'Coil',            price = 340000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'entity2',         name = 'Entity XXR',                    brand = 'Överflöd',        price = 415000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'entityxf',        name = 'Entity XF',                     brand = 'Överflöd',        price = 420000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'emerus',          name = 'Emerus',                        brand = 'Progen',          price = 375000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'fmj',             name = 'FMJ',                           brand = 'Vapid',           price = 390000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'furia',           name = 'Furia',                         brand = 'Grotti',          price = 530000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'gp1',             name = 'GP1',                           brand = 'Progen',          price = 415000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'infernus',        name = 'Infernus',                      brand = 'Pegassi',         price = 430000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'italigtb',        name = 'Itali GTB',                     brand = 'Progen',          price = 410000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'italigtb2',       name = 'Itali GTB Custom',              brand = 'Progen',          price = 440000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'krieger',         name = 'Krieger',                       brand = 'Benefactor',      price = 490000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'le7b',            name = 'RE-7B',                         brand = 'Annis',           price = 420000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'nero',            name = 'Nero',                          brand = 'Truffade',        price = 460000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'nero2',           name = 'Nero Custom',                   brand = 'Truffade',        price = 440000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'osiris',          name = 'Osiris',                        brand = 'Pegassi',         price = 390000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'penetrator',      name = 'Penetrator',                    brand = 'Ocelot',          price = 390000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'penetrator',      name = 'Penetrator',                    brand = 'Ocelot',          price = 390000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'pfister811',      name = '811',                           brand = 'Pfister',         price = 380000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'prototipo',       name = 'X80 Proto',                     brand = 'Grotti',          price = 595000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'reaper',          name = 'Reaper',                        brand = 'Pegassi',         price = 460000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 's80',             name = 'S80RR',                         brand = 'Annis',           price = 420000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'sc1',             name = 'SC1',                           brand = 'Übermacht',       price = 370000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'sheava',          name = 'ETR1',                          brand = 'Emperor',         price = 490000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 't20',             name = 'T20',                           brand = 'Progen',          price = 560000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'taipan',          name = 'Taipan',                        brand = 'Cheval',          price = 540000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'tempesta',        name = 'Tempesta',                      brand = 'Pegassi',         price = 510000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'tezeract',        name = 'Tezeract',                      brand = 'Pegassi',         price = 470000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'thrax',           name = 'Thrax',                         brand = 'Truffade',        price = 520000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'tigon',           name = 'Tigon',                         brand = 'Lampadati',       price = 420000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'turismor',        name = 'Turismo R',                     brand = 'Grotti',          price = 415000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'tyrant',          name = 'Tyrant',                        brand = 'Överflöd',        price = 515000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'tyrus',           name = 'Tyrus',                         brand = 'Progen',          price = 470000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'vacca',           name = 'Vacca',                         brand = 'Pegassi',         price = 365000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'vagner',          name = 'Vagner',                        brand = 'Dewbauchee',      price = 490000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'voltic',          name = 'Voltic',                        brand = 'Coil',            price = 390000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'xa21',            name = 'XA-21',                         brand = 'Ocelot',          price = 440000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'zentorno',        name = 'Zentorno',                      brand = 'Pegassi',         price = 595000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'zorrusso',        name = 'Zorrusso',                      brand = 'Pegassi',         price = 417000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'ignus',           name = 'Ignus',                         brand = 'Pegassi',         price = 539500,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'zeno',            name = 'Zeno',                          brand = 'Överflöd',        price = 515600,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'deveste',         name = 'Deveste',                       brand = 'Principe',        price = 394000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'lm87',            name = 'LM87',                          brand = 'Benefactor',      price = 390000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'torero2',         name = 'Torero XO',                     brand = 'Pegassi',         price = 385000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'entity3',         name = 'Entity MT',                     brand = 'Overflod',        price = 420000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'virtue',          name = 'Virtue',                        brand = 'Ocelot',          price = 485000,  category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'turismo3',        name = 'Turismo Omaggio',               brand = 'Grotti',          price = 404500,  category = 'super',          type = 'automobile', shop = 'pdm' },


    { model = 'africat', name = 'AFRICAT', brand = 'Progen', price = 100000, category = 'donate', type = 'bike', shop = 'donate' },
    { model = 'flhxs_streetglide_special18', name = 'FLHXS_STREETGLIDE_SPECIAL18', brand = 'Progen', price = 100000, category = 'donate', type = 'bike', shop = 'donate' },
    { model = 'jax2', name = 'JAX2', brand = 'Progen', price = 100000, category = 'donate', type = 'bike', shop = 'donate' },
    { model = 'lpbagger2', name = 'LPBAGGER2', brand = 'Progen', price = 100000, category = 'donate', type = 'bike', shop = 'donate' },
    { model = 'mt09', name = 'MT09', brand = 'Progen', price = 100000, category = 'donate', type = 'bike', shop = 'donate' },
    { model = 'nh2r', name = 'NH2R', brand = 'Progen', price = 100000, category = 'donate', type = 'bike', shop = 'donate' },
    { model = 'panigale', name = 'PANIGALE', brand = 'Progen', price = 100000, category = 'donate', type = 'bike', shop = 'donate' },
    { model = 'r1', name = 'R1', brand = 'Progen', price = 100000, category = 'donate', type = 'bike', shop = 'donate' },
    { model = 'r6', name = 'R6', brand = 'Progen', price = 100000, category = 'donate', type = 'bike', shop = 'donate' },
    { model = 's1000rr', name = 'S1000RR', brand = 'Progen', price = 100000, category = 'donate', type = 'bike', shop = 'donate' },
    { model = 'SnBladec', name = 'SNBLADEC', brand = 'Progen', price = 100000, category = 'donate', type = 'bike', shop = 'donate' },
    { model = 'softail1', name = 'SOFTAIL1', brand = 'Progen', price = 100000, category = 'donate', type = 'bike', shop = 'donate' },
    { model = 'vrodft', name = 'VRODFT', brand = 'Progen', price = 100000, category = 'donate', type = 'bike', shop = 'donate' },
    { model = 'zx10r', name = 'ZX10R', brand = 'Progen', price = 100000, category = 'donate', type = 'bike', shop = 'donate' },
    { model = 'lapdmotor', name = 'LAPDMOTOR', brand = 'Progen', price = 100000, category = 'donate', type = 'bike', shop = 'donate' },
    { model = 'pbike', name = 'PBIKE', brand = 'Progen', price = 100000, category = 'donate', type = 'bike', shop = 'donate' },
    { model = 'amgh', name = 'AMGH', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'ap2', name = 'AP2', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'cls63s', name = 'CLS63S', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FL812', name = 'FL812', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'golf8', name = 'GOLF8', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'p1gtr', name = 'P1GTR', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rmodr8c', name = 'RMODR8C', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = '16m3f80', name = '16M3F80', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = '23touring', name = '23TOURING', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'bmwg07', name = 'BMWG07', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'charger21', name = 'CHARGER21', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'e60', name = 'E60', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'evo9', name = 'EVO9', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FL918s', name = 'FL918S', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLclass', name = 'FLCLASS', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLe63s', name = 'FLE63S', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLevo', name = 'FLEVO', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLtrx', name = 'FLTRX', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'gt86', name = 'GT86', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'hurevos', name = 'HUREVOS', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'm3g80', name = 'M3G80', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'mercedessl63', name = 'MERCEDESSL63', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'mustang19', name = 'MUSTANG19', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'pista', name = 'PISTA', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rmodamggt', name = 'RMODAMGGT', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rmodmi8lb', name = 'RMODMI8LB', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rmodpanamera2', name = 'RMODPANAMERA2', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rmods63', name = 'RMODS63', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rs615', name = 'RS615', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'sf90', name = 'SF90', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'skyline', name = 'SKYLINE', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'tacoma24', name = 'TACOMA24', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'thebugpfl', name = 'THEBUGPFL', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'wraithb', name = 'WRAITHB', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'x5bmw', name = 'X5BMW', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'gtrsllb', name = 'GTRSLLB', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'gtz34', name = 'GTZ34', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'mkcr33', name = 'MKCR33', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'protoz', name = 'PROTOZ', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rmodz350pandem', name = 'RMODZ350PANDEM', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rmx7hycade', name = 'RMX7HYCADE', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'topfoil', name = 'TOPFOIL', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLcharger', name = 'FLCHARGER', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLemsf', name = 'FLEMSF', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLemsh', name = 'FLEMSH', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLspeedo', name = 'FLSPEEDO', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLtau', name = 'FLTAU', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'adrom4', name = 'ADROM4', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'DBdc_s500mansory', name = 'DBDC_S500MANSORY', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FL812ss', name = 'FL812SS', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLb7', name = 'FLB7', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLbentley', name = 'FLBENTLEY', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLc8', name = 'FLC8', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLetrongt', name = 'FLETRONGT', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLm3', name = 'FLM3', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLrev', name = 'FLREV', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLrs7', name = 'FLRS7', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'gcbx5', name = 'GCBX5', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'mi8', name = 'MI8', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'miniclw', name = 'MINICLW', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rs6abtp', name = 'RS6ABTP', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'deluxo6str', name = 'DELUXO6STR', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'domgtcoupe', name = 'DOMGTCOUPE', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'elegyrh6', name = 'ELEGYRH6', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'elegyrh7', name = 'ELEGYRH7', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'elegy2', name = 'ELEGY2', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'eurosx32wb', name = 'EUROSX32WB', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'infernuswb', name = 'INFERNUSWB', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'jestgpr', name = 'JESTGPR', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'jugularrest', name = 'JUGULARREST', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'schwarzer2', name = 'SCHWARZER2', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'sentinel6str2', name = 'SENTINEL6STR2', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'sheavas', name = 'SHEAVAS', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'sultanrsv82', name = 'SULTANRSV82', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'sunrise1', name = 'SUNRISE1', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'tfremus', name = 'TFREMUS', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'yosemite6str', name = 'YOSEMITE6STR', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'zr390', name = 'ZR390', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'zr3806str', name = 'ZR3806STR', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'zrgpr', name = 'ZRGPR', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'buffalosxumk', name = 'BUFFALOSXUMK', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'cat', name = 'CAT', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'fattorrence', name = 'FATTORRENCE', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'hazard2', name = 'HAZARD2', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'ucbailer', name = 'UCBAILER', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'ucwashington', name = 'UCWASHINGTON', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'ussssuv', name = 'USSSSUV', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'centurion', name = 'CENTURION', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'pdtekne', name = 'PDTEKNE', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = '22m5', name = '22M5', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = '675ltsp', name = '675LTSP', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = '911brabus', name = '911BRABUS', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'c63spd', name = 'C63SPD', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'f8spider', name = 'F8SPIDER', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'f82', name = 'F82', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FL488', name = 'FL488', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'Fldemon', name = 'FLDEMON', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLe46', name = 'FLE46', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLram', name = 'FLRAM', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'gt3hycade', name = 'GT3HYCADE', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'gtr', name = 'GTR', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'm4comp', name = 'M4COMP', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'm5g60', name = 'M5G60', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'nissantitan17', name = 'NISSANTITAN17', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rmod911gt3', name = 'RMOD911GT3', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rmodg63', name = 'RMODG63', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rmodg900', name = 'RMODG900', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rmodgt63', name = 'RMODGT63', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rmodm4gts', name = 'RMODM4GTS', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rmodx61', name = 'RMODX61', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'senna', name = 'SENNA', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'toysupmk4', name = 'TOYSUPMK4', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'urus', name = 'URUS', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'bimx', name = 'BIMX', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLcatcar', name = 'FLCATCAR', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLraid', name = 'FLRAID', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'jogger', name = 'JOGGER', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'm31', name = 'M31', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'newsmav', name = 'NEWSMAV', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'newsvan', name = 'NEWSVAN', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'newsvan2', name = 'NEWSVAN2', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'sbus2', name = 'SBUS2', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'sfg50fly', name = 'SFG50FLY', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'taco2', name = 'TACO2', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'bmw8mm', name = 'BMW8MM', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'bmw8pd', name = 'BMW8PD', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'FLlambo', name = 'FLLAMBO', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'M3BXANF', name = 'M3BXANF', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rmodm8c', name = 'RMODM8C', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'soulcarrier', name = 'SOULCARRIER', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'polnspeedo', name = 'POLNSPEEDO', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'e15082', name = 'E15082', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'reaper1', name = 'REAPER1', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'rumpo', name = 'RUMPO', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'cat_car', name = 'CAT_CAR', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'calchop', name = 'CALCHOP', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'cvo', name = 'CVO', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
    { model = 'newsheli', name = 'NEWSHELI', brand = 'Progen', price = 100000, category = 'donate', type = 'automobile', shop = 'donate' },
}

for i = 1, #Vehicles do
    QBShared.Vehicles[Vehicles[i].model] = {
        spawncode = Vehicles[i].model,
        name = Vehicles[i].name,
        brand = Vehicles[i].brand,
        model = Vehicles[i].model,
        price = Vehicles[i].price,
        category = Vehicles[i].category,
        hash = joaat(Vehicles[i].model),
        type = Vehicles[i].type,
        shop = Vehicles[i].shop
    }
end